#!/bin/bash

read -r -d '' CONFIGMSG <<'END_HEREDOC'
#   _____      _                
#  / ____|    | |               
# | |     ___ | | ___  _ __ ___ 
# | |    / _ \| |/ _ \| '__/ __|
# | |___| (_) | | (_) | |  \__ \
#  \_____\___/|_|\___/|_|  |___/
#
# This template section was automatically genereated. Please see $CONFIG/themes/* 
# for examples!
END_HEREDOC

function parse_yaml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("set $%s%s%s %s\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

if [ -f $1 ]; then
    echo "$CONFIGMSG"
    parse_yaml $1
fi
