#!/bin/bash
# Multihead mode switch

CONFIG="$HOME/.dotfiles/i3/config"

# Grab monitor names from the i3 config
mon0="$(cat "$CONFIG" | grep set | grep mon0 | cut -d " " -f 3)"
mon1="$(cat "$CONFIG" | grep set | grep mon1 | cut -d " " -f 3)"
mon2="$(cat "$CONFIG" | grep set | grep mon2 | cut -d " " -f 3)"

docked_wrkstat() {
    xrandr --output $mon0 --off
    xrandr --output $mon1 --auto --output $mon2 --auto --left-of $mon1 --primary
}

docked_tvmode() { 
    xrandr --output $mon0 --off
    xrandr --output $mon1 --auto --output $mon2 --auto --right-of $mon1 --primary
}

undocked() {
    xrandr --output $mon1 --off --output $mon2 --off
    xrandr --output $mon0 --auto
}

case $1 in
    1) docked_wrkstat;;
    2) undocked;;
    3) docked_tvmode;;
    *) echo "$0 <option>; 1: docked workstation mode, 2: undocked mode, 3: docked tv mode";;
esac

# Restore wallpaper settings
nitrogen --restore
