#!/bin/bash

CONFIGD=$HOME/.config/i3

CUSTOM="$HOME/.config/i3/themes"
DEFAULT="/lib/node_modules/i3-style/themes"

MENUTEXT="You can use the UP/DOWN arrow keys, the first \n\
    letter of the choice as a hot key, or the \n\
    number keys 1-9 to choose an option.\n\
    Choose the THEME"

# Draw theme selection menu and handle input

draw_theme_menu () {

    SOURCE=$2
    THEMES=() # working array of themes
    let i=0 # counter
    while read -r line; do
        let i=$i+1
        THEMES+=($i "$line")
    done < <(ls -1 "$SOURCE")
    
    OPTION=$(dialog --clear --backtitle "[ I3 CONFIGURATOR ]" \
    --title "$1" \
    --menu "$MENUTEXT" 15 50 4 \
    "${THEMES[@]}" 3>&2 2>&1 1>&3)

    if [ $? -eq 0 ]; then # Exit with OK
        result=$(ls -1 $SOURCE | sed -n "`echo "$OPTION p" | sed 's/ //'`")
        i3-style $SOURCE/$result -o $CONFIGD/config --reload > /dev/null
    fi

}

#draw_main_menu () {
#    OPTION=$(dialog --clear --backtitle
#}

draw_theme_menu "[ DEFAULT - THEMES ]" $DEFAULT
